image: node:alpine

cache:
  paths:
    - node_modules/

test:
  script:
    - npm install
    - CI=true npm run test -- --coverage

pages:
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
